[package]
name = "cali"
version = "0.2.0"
edition = "2024"
description = "A terminal calculator with real-time evaluation, unit conversions, and natural language expressions."

[dependencies]
ratatui = "0.25.0"
crossterm = "0.27.0"
tui-input = "0.8.0"
evalexpr = "11.3.0"
chrono = "0.4.35"
pest = "2.7.7"
pest_derive = "2.7.7"
regex = "1.10.3"
rust_decimal = "1.34.2"
thiserror = "1.0.56"
once_cell = "1.10.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
