name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install release tools
        run: |
          cargo install cargo-dist

      - name: Build and package
        run: cargo dist build --target=x86_64-unknown-linux-gnu --target=x86_64-pc-windows-gnu --target=x86_64-apple-darwin

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/dist/*.tar.gz
            target/dist/*.zip
            target/dist/*.msi
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true 